"""Tried assosiation table

Revision ID: 10319f692463
Revises: 72634c7ecb5b
Create Date: 2020-02-19 08:33:51.412812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10319f692463'
down_revision = '72634c7ecb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tried',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('strain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tried')
    # ### end Alembic commands ###
