"""User and Strain Tables

Revision ID: 48219eba7458
Revises: 
Create Date: 2020-02-17 14:58:06.127794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48219eba7458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=25), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('leafly', sa.String(length=50), nullable=True),
    sa.Column('species', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leafly')
    )
    op.create_index(op.f('ix_strain_index'), 'strain', ['index'], unique=True)
    op.create_index(op.f('ix_strain_name'), 'strain', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_strain_name'), table_name='strain')
    op.drop_index(op.f('ix_strain_index'), table_name='strain')
    op.drop_table('strain')
    # ### end Alembic commands ###
