"""removed unique index from strain name

Revision ID: 72634c7ecb5b
Revises: 48219eba7458
Create Date: 2020-02-17 15:08:35.403712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72634c7ecb5b'
down_revision = '48219eba7458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strain_name', table_name='strain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_strain_name', 'strain', ['name'], unique=1)
    # ### end Alembic commands ###
